services:
  - mysql

before_install:
  - curl -fsSL https://deno.land/x/install/install.sh | sh
  - export PATH="/home/travis/.deno/bin:$PATH"

script:
  - deno test --unstable --allow-net -c tsconfig.json test.ts
