name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        deno: ["v1.2.1"]
    name: Deno ${{ matrix.deno }}

    services:
      mysql:
        image: mysql:8.0.21
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
          MYSQL_ROOT_PASSWORD: ""
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3 

      postgres:
       image: postgres:11.5
       ports:
        - 5432:5432
       env:
        POSTGRES_USER: "thankgodukachukwu"
        POSTGRES_PASSWORD: "test_orm" 
        POSTGRES_DB: "test_orm"
      sqlite:
        image: sqlite3
      

    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - name: Check format
        run: |
          deno fmt --check
      - name: Test
        run: |
          deno test --allow-net  --allow-read --allow-write -c tsconfig.json
